# Generated by Django 4.2.3 on 2025-01-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='magazines/covers/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(upload_to='magazines/pdfs/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
