# Generated by Django 4.2.3 on 2025-01-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_magazine_cover_image_alter_magazine_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='cover_image',
            field=models.ImageField(default=0, upload_to='magazines/covers/'),
            preserve_default=False,
        ),
    ]
